
options:
  machineType: 'E2_HIGHCPU_32'
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: dockersecret
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$_USERNAME --password=$$PASSWORD']
  secretEnv: ['PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  id: 'initialize-qemu'
  args: ['run', '--privileged', '--rm', 'tonistiigi/binfmt', '--install', 'all']
  waitFor: ['dockersecret']
- name: 'gcr.io/cloud-builders/docker'
  id: 'create-and-select-builder'
  args: ['buildx', 'create', '--name', 'multi-arch-builder', '--use']
  waitFor: ['initialize-qemu']
- name: 'gcr.io/cloud-builders/docker'
  id: alpine
  args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '-t', 'google/cloud-sdk:alpine', '-t', 'google/cloud-sdk:$TAG_NAME-alpine', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine', '--push', 'alpine/']
  waitFor: ['create-and-select-builder']
- name: 'gcr.io/cloud-builders/docker'
  id: debian_slim
  args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '-t', 'google/cloud-sdk:slim', '-t', 'google/cloud-sdk:$TAG_NAME-slim', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:slim', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:slim', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:slim', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim', '--push', 'debian_slim/']
  waitFor: ['create-and-select-builder']
- name: 'gcr.io/cloud-builders/docker'
  id: default
  args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '-t', 'google/cloud-sdk:latest', '-t', 'google/cloud-sdk:$TAG_NAME', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:latest', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:latest', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:latest', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:latest', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:latest', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:latest', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME', '--push', '.']
  waitFor: ['create-and-select-builder']
- name: 'gcr.io/cloud-builders/docker'
  id: debian_component_based
  args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '-t', 'google/cloud-sdk:debian_component_based', '-t', 'google/cloud-sdk:$TAG_NAME-debian_component_based', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-debian_component_based', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-debian_component_based', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-debian_component_based', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-debian_component_based', '--push', 'debian_component_based/']
  waitFor: ['create-and-select-builder']
- name: 'gcr.io/cloud-builders/docker'
  id: emulators
  args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '-t', 'google/cloud-sdk:emulators', '-t', 'google/cloud-sdk:$TAG_NAME-emulators', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:emulators', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators', '-t', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-emulators', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators', '-t', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-emulators', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators', '-t', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-emulators', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators', '-t', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-emulators', '--push', 'emulators/']
  waitFor: ['create-and-select-builder']
images:
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME'
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine'
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based'
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators'
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim'
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based'
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators'
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
- 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-debian_component_based'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-emulators'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
- 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
- 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-debian_component_based'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-emulators'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
- 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:emulators'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
- 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-debian_component_based'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-emulators'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
- 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
- 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-debian_component_based'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-emulators'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
- 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
secrets:
- kmsKeyName: projects/google.com:cloudsdktool/locations/global/keyRings/docker/cryptoKeys/dockerhub-password
  secretEnv:
    PASSWORD: |
        CiQA9btlfpg/kWmwXQvrNXtkVpu2tDdD2VOi1FYd3mmjCUGaK4YSNwC8sn1MepjracHAg8VAQEWm
        s26BTGccqD1NTS83DGFdY9moRGhSPm4WJKCg2tTQKYeTfdqUjjM=
timeout: 7200s
options:
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'
substitutions:
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm/v7,linux/arm64'
