# PROD BUILDING STEPS
options:
  machineType: 'E2_HIGHCPU_32'
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: alpine
  args: ['build', '-t', 'google/cloud-sdk:alpine', '-t', 'google/cloud-sdk:$TAG_NAME-alpine', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine', 'alpine/']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: debian_slim
  args: ['build', '-t', 'google/cloud-sdk:slim', '-t', 'google/cloud-sdk:$TAG_NAME-slim', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:slim', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:slim', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:slim', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim', 'debian_slim/']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: default
  args: ['build', '-t', 'google/cloud-sdk:latest', '-t', 'google/cloud-sdk:$TAG_NAME', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:latest', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:latest', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:latest', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME', '.']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: debian_component_based
  args: ['build', '-t', 'google/cloud-sdk:debian_component_based', '-t', 'google/cloud-sdk:$TAG_NAME-debian_component_based', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based', 'debian_component_based/']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: emulators
  args: ['build', '-t', 'google/cloud-sdk:emulators', '-t', 'google/cloud-sdk:$TAG_NAME-emulators', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:emulators', '-t', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators', '-t', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators', '-t', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators', '-t', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators', 'emulators/']
  waitFor: ['-']
# END OF PROD BUILDING STEPS
- name: 'gcr.io/cloud-builders/docker'
  id: dockersecret
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$_USERNAME --password=$$PASSWORD']
  secretEnv: ['PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:alpine']
  waitFor: ['dockersecret', 'alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:$TAG_NAME-alpine']
  waitFor: ['dockersecret', 'alpine']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine']
  waitFor: ['dockersecret', 'alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine']
  waitFor: ['dockersecret', 'alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine']
  waitFor: ['dockersecret', 'alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:alpine']
  waitFor: ['dockersecret', 'alpine']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine']
  waitFor: ['dockersecret', 'alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine']
  waitFor: ['dockersecret', 'alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine']
  waitFor: ['dockersecret', 'alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-alpine']
  waitFor: ['dockersecret', 'alpine']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:slim']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:$TAG_NAME-slim']
  waitFor: ['dockersecret', 'debian_slim']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:slim']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:slim']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:slim']
  waitFor: ['dockersecret', 'debian_slim']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:slim']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-slim']
  waitFor: ['dockersecret', 'debian_slim']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:latest']
  waitFor: ['dockersecret', 'default']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:$TAG_NAME']
  waitFor: ['dockersecret', 'default']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:latest']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:latest']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:latest']
  waitFor: ['dockersecret', 'debian_slim']


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME']
  waitFor: ['dockersecret', 'debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME']
  waitFor: ['dockersecret', 'debian_slim']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:$TAG_NAME-debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-debian_component_based']
  waitFor: ['dockersecret', 'debian_component_based']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:emulators']
  waitFor: ['dockersecret', 'emulators']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'google/cloud-sdk:$TAG_NAME-emulators']
  waitFor: ['dockersecret', 'emulators']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:emulators']
  waitFor: ['dockersecret', 'emulators']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators']
  waitFor: ['dockersecret', 'emulators']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators']
  waitFor: ['dockersecret', 'emulators']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators']
  waitFor: ['dockersecret', 'emulators']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators']
  waitFor: ['dockersecret', 'emulators']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators']
  waitFor: ['dockersecret', 'emulators']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators']
  waitFor: ['dockersecret', 'emulators']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/cloud-sdk:$TAG_NAME-emulators']
  waitFor: ['dockersecret', 'emulators']
## Rebrand google-cloud-cli publis steps
# alpine
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_alpine_1
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine']
  waitFor: ['alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine']
  waitFor: ['google_cloud_cli_tag_alpine_1']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_alpine_2
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine']
  waitFor: ['alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine']
  waitFor: ['google_cloud_cli_tag_alpine_2']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_alpine_3
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine']
  waitFor: ['alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine']
  waitFor: ['google_cloud_cli_tag_alpine_3']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_alpine_4
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine']
  waitFor: ['alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine']
  waitFor: ['google_cloud_cli_tag_alpine_4']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_alpine_5
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine']
  waitFor: ['alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine']
  waitFor: ['google_cloud_cli_tag_alpine_5']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_alpine_6
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine']
  waitFor: ['alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine']
  waitFor: ['google_cloud_cli_tag_alpine_6']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_alpine_7
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine']
  waitFor: ['alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine']
  waitFor: ['google_cloud_cli_tag_alpine_7']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_alpine_8
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine']
  waitFor: ['alpine']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-alpine']
  waitFor: ['google_cloud_cli_tag_alpine_8']
# debian_slim
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_debian_slim_1
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim']
  waitFor: ['debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim']
  waitFor: ['google_cloud_cli_tag_debian_slim_1']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_debian_slim_2
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim']
  waitFor: ['debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim']
  waitFor: ['google_cloud_cli_tag_debian_slim_2']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_debian_slim_3
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim']
  waitFor: ['debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim']
  waitFor: ['google_cloud_cli_tag_debian_slim_3']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_debian_slim_4
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim']
  waitFor: ['debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim']
  waitFor: ['google_cloud_cli_tag_debian_slim_4']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_debian_slim_5
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim']
  waitFor: ['debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim']
  waitFor: ['google_cloud_cli_tag_debian_slim_5']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_debian_slim_6
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim']
  waitFor: ['debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim']
  waitFor: ['google_cloud_cli_tag_debian_slim_6']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_debian_slim_7
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim']
  waitFor: ['debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:slim']
  waitFor: ['google_cloud_cli_tag_debian_slim_7']
- name: 'gcr.io/cloud-builders/docker'
  id: google_cloud_cli_tag_debian_slim_8
  args: ['tag', 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim']
  waitFor: ['debian_slim']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/google.com/cloudsdktool/google-cloud-cli:$TAG_NAME-slim']
  waitFor: ['google_cloud_cli_tag_debian_slim_8']
# default
# debian_component_based
# emulators

secrets:
- kmsKeyName: projects/google.com:cloudsdktool/locations/global/keyRings/docker/cryptoKeys/dockerhub-password
  secretEnv:
    PASSWORD: |
        CiQA9btlfpg/kWmwXQvrNXtkVpu2tDdD2VOi1FYd3mmjCUGaK4YSNwC8sn1MepjracHAg8VAQEWm
        s26BTGccqD1NTS83DGFdY9moRGhSPm4WJKCg2tTQKYeTfdqUjjM=
timeout: 7200s
